### ISSUE TITLE
Documentation of the annot

### ISSUE THREAD

**Issue by bsridatta** [juyongchang/PoseLifter#2]
Thanks a lot for the data and annotations! Could you provide any link to how those annotations were made? I didn't quite understand how pose3d differ from pose3d_global. Is pose3d obtained by converting pose3d_global to camera coordinates? which inturn is projected as pose2d? 
Could you please clarify on these preprocessing steps to get the data in annot.

Thanks a lot.

**Comment by juyongchang** [comment]
I have uploaded a matlab script file that generates human3.6m raw dataset files. Please refer to the following [link](https://github.com/juyongchang/PoseLifter/blob/master/src/matlab/create_dataset_h36m.m). To run this script you will need the code of human3.6m authors.

**Comment by bsridatta** [comment]
Thank you!
