### ISSUE TITLE
mpii-inf-3dhp calibration

### ISSUE THREAD

**Issue by vru2020** [juyongchang/PoseLifter#3]
@juyongchang thanks for making your code public. I am trying to train on MPII-INF-3DHP. I need to do 2D projection using calibration matrices. When I use the data you provided and the camera parameters from the original dataset, the projection is wrong. Have you done any postprocessing to the data (translation or something similar ?) Thanks for your help

**Comment by juyongchang** [comment]
The image I provided was obtained by cropping the original image using bounding box information and resizing the result to 256x256 size. And, the camera parameters in the original dataset are for the original image and cannot be applied directly to the 256x256 size image. You can apply cropping and resizing to the original image by using the bounding box information included in the annotation file provided by me. I hope my answer is helpful.
